<?php

/**
 * aInsetImageSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aInsetImageSlotTable extends PluginaInsetImageSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aInsetImageSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aInsetImageSlot');
    }
}