<?php

/**
 * aInsetAreaSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aInsetAreaSlotTable extends PluginaInsetAreaSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aInsetAreaSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aInsetAreaSlot');
    }
}