default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - main.css: { position: last }
    - /apostropheExtraSlotsPlugin/css/aExtraSlots.css

  javascripts:
    - /apostropheBlogPlugin/js/aBlog.js           # Required for blog plugin
    - site.js: { position: last }

  has_layout:     true
  layout:         layout
