<?php

/**
 * BaseaAreaVersion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $area_id
 * @property integer $version
 * @property integer $author_id
 * @property string $diff
 * @property aArea $Area
 * @property sfGuardUser $Author
 * @property Doctrine_Collection $AreaVersionSlots
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method integer             getAreaId()           Returns the current record's "area_id" value
 * @method integer             getVersion()          Returns the current record's "version" value
 * @method integer             getAuthorId()         Returns the current record's "author_id" value
 * @method string              getDiff()             Returns the current record's "diff" value
 * @method aArea               getArea()             Returns the current record's "Area" value
 * @method sfGuardUser         getAuthor()           Returns the current record's "Author" value
 * @method Doctrine_Collection getAreaVersionSlots() Returns the current record's "AreaVersionSlots" collection
 * @method aAreaVersion        setId()               Sets the current record's "id" value
 * @method aAreaVersion        setAreaId()           Sets the current record's "area_id" value
 * @method aAreaVersion        setVersion()          Sets the current record's "version" value
 * @method aAreaVersion        setAuthorId()         Sets the current record's "author_id" value
 * @method aAreaVersion        setDiff()             Sets the current record's "diff" value
 * @method aAreaVersion        setArea()             Sets the current record's "Area" value
 * @method aAreaVersion        setAuthor()           Sets the current record's "Author" value
 * @method aAreaVersion        setAreaVersionSlots() Sets the current record's "AreaVersionSlots" collection
 * 
 * @package    asandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseaAreaVersion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('a_area_version');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('area_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('version', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('diff', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));


        $this->index('area_index', array(
             'fields' => 
             array(
              0 => 'area_id',
             ),
             ));
        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('aArea as Area', array(
             'local' => 'area_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('sfGuardUser as Author', array(
             'local' => 'author_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('aAreaVersionSlot as AreaVersionSlots', array(
             'local' => 'id',
             'foreign' => 'area_version_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}