<?php

/**
 * BaseaFileSlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    asandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseaFileSlot extends aSlot
{
    public function setUp()
    {
        parent::setUp();
        
    }
}