<?php

/**
 * aAudioSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aAudioSlotTable extends PluginaAudioSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aAudioSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aAudioSlot');
    }
}