<?php

/**
 * aCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aCategoryTable extends PluginaCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aCategory');
    }
}