<?php

/**
 * aCategoryUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aCategoryUserTable extends PluginaCategoryUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aCategoryUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aCategoryUser');
    }
}