<?php

/**
 * aEmbedMediaAccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aEmbedMediaAccountTable extends PluginaEmbedMediaAccountTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aEmbedMediaAccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aEmbedMediaAccount');
    }
}