<?php

/**
 * aFileSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aFileSlotTable extends PluginaFileSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aFileSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aFileSlot');
    }
}