<?php

/**
 * aMediaItemToCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aMediaItemToCategoryTable extends PluginaMediaItemToCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aMediaItemToCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aMediaItemToCategory');
    }
}