<?php

/**
 * aPageToCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aPageToCategoryTable extends PluginaPageToCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aPageToCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aPageToCategory');
    }
}