<?php

/**
 * aSmartSlideshowSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aSmartSlideshowSlotTable extends PluginaSmartSlideshowSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aSmartSlideshowSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aSmartSlideshowSlot');
    }
}