<?php

/**
 * PluginaInsetImageSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaInsetImageSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaInsetImageSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaInsetImageSlot');
    }
}