<?php

/**
 * PluginaInsetAreaSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaInsetAreaSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaInsetAreaSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaInsetAreaSlot');
    }
}