<?php

/**
 * BaseaBlogItemToCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $blog_item_id
 * @property integer $category_id
 * @property aBlogItem $BlogItem
 * @property aCategory $Category
 * 
 * @method integer             getBlogItemId()   Returns the current record's "blog_item_id" value
 * @method integer             getCategoryId()   Returns the current record's "category_id" value
 * @method aBlogItem           getBlogItem()     Returns the current record's "BlogItem" value
 * @method aCategory           getCategory()     Returns the current record's "Category" value
 * @method aBlogItemToCategory setBlogItemId()   Sets the current record's "blog_item_id" value
 * @method aBlogItemToCategory setCategoryId()   Sets the current record's "category_id" value
 * @method aBlogItemToCategory setBlogItem()     Sets the current record's "BlogItem" value
 * @method aBlogItemToCategory setCategory()     Sets the current record's "Category" value
 * 
 * @package    asandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseaBlogItemToCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('a_blog_item_to_category');
        $this->hasColumn('blog_item_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('aBlogItem as BlogItem', array(
             'local' => 'blog_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('aCategory as Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}