<?php

/**
 * aBlogItemToCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aBlogItemToCategoryTable extends PluginaBlogItemToCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aBlogItemToCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aBlogItemToCategory');
    }
}